apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: hypercloud4-workflow-mutator
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lKQU8rSE5KZm1HVGNSTUEwR0NTcUdTSWIzRFFFQkN3VUFNQmt4RnpBVkJnTlYKQkFNTURuZHBibVJ2ZHlCM1pXSm9iMjlyTUI0WERUSXdNVEl5TkRBNE5EY3hOVm9YRFRJeE1ERXlNekE0TkRjeApOVm93R1RFWE1CVUdBMVVFQXd3T2QybHVaRzkzSUhkbFltaHZiMnN3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBCkE0SUJEd0F3Z2dFS0FvSUJBUUNkeE03OWNnSmhZOXR2aHVFWDZqTHdwWFNlZTFmNHFoT29rU3RMcTJKdE02NFYKUlhmTzhRRHBmVHFvREdXanE1ZGNwYkR4a1pWbittbFdJK2p5MXpERGhid1lXU0JDbnEwdStrV1FpNFdDOGl0Ywo4cXU3T0w2ckJSV1Z5ajd6bEl1TTYxUXNJb1BuVVJMZVFSektndVM4eklHYXFKbVh5M3JwVmhzeXpXWFd1YjFHCnJ3eXlVLzdEQW50Z1hNKzhqK2M3VW1NZDI3TkY3Ui9iODdLb0JEelpVODNLNkpZeDJldkNZUWhtSndmcVpCZGgKMU1mZ3A2NnowQ2Q1VVEvd3dSUUZQeSs0YkxpbTFXQkpRVnYybFNraHNxMjEwcnc2dk1ldE0vVHllZnhQYVYycQpZM2EwQ285R1pnYzdEQmRXSGJYcmFnR2N1aWVhZURwdmI0TWVoUDE5QWdNQkFBR2pVREJPTUIwR0ExVWREZ1FXCkJCVDJBbG1jTE14N3RJek15cXFlQklzVHFQVHAyREFmQmdOVkhTTUVHREFXZ0JUMkFsbWNMTXg3dEl6TXlxcWUKQklzVHFQVHAyREFNQmdOVkhSTUVCVEFEQVFIL01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQjJpbExNOGE1eApHYW5QRVFMSFlKcHhqdFk2bnJWMEZXVmQ1UW1xR09wanpMMkRWVy8rcEp5WnFDOVJNeWpVR2ZhWXNTWnNsMnpNCmtRakh0THEydnJ1RG04a0ZCT01HSFByOXFIcVJnelZld1oyRm1TTUVCZm1JSUh6MHJOWWw1S3NmMHdackVSbFcKTUNoOHRZbEtteTNjNlNHUDMxY3laN0Z4bWlyTFBBVEZpZnl1K3JFeEVXZUQrMHBlZFRYd3gzamdLSU9paFRVdApBT284QllYRWY4UHg2RDRJMEZLZnlySU52Zmk0MDF3MSsxaUtobHdUeW5kV2FWbll0OGV5M0hNa0JEWkduL1ZUCm1WL1RRR1R3WFd3VmFyWW1NZWxYUVIwNDluQ3hlMHF4Z0VYRmtYaG5rNjFITElSWW1MUFl2QUNMVDQySUdDYWMKRlBzWEhXWFZHd3pZCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: hypercloud4-workflow-webhook-svc
      namespace: hypercloud4-system
      path: /api/webhook/metadata 
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: hypercloud4-workflow-webhook-svc.hypercloud4-system.svc
  namespaceSelector:
    matchExpressions:
    - key: workflow-webhook
      operator: NotIn
      values:
      - "false"
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - argoproj.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - Workflow
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
