apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: hypercloud4-workflow-mutator
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: {{CA_PEM_BASE64}}
    service:
      name: hypercloud4-workflow-webhook-svc
      namespace: hypercloud4-system
      path: /api/webhook/metadata 
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: hypercloud4-workflow-webhook-svc.hypercloud4-system.svc
  namespaceSelector:
    matchExpressions:
    - key: workflow-webhook
      operator: NotIn
      values:
      - "false"
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - argoproj.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - Workflow,WorkflowTemplate
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
